[project]
name = "rnns-jax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.2",
    "flax>=0.12.8",
    "jax>=0.10.2",
    "omegaconf>=2.3.1",
    "optax>=0.2.8",
    "orbax-checkpoint>=0.12.6",
    "polars>=1.44.2",
    "pyarrow>=25.0.1",
    "tensorboardx>=2.6.5",
    "tqdm>=4.70.1",
]

[tool.setuptools]
packages = ["models", "util"]
